trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: Test

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: replacetokens@6
  inputs:
    sources: 'pom.xml'
    tokenPattern: 'azpipelines'
  displayName: Token coniguration 

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      cd $(build.sourcesDirectory)
      ls
      pwd
      cat pom.xml
      git fsck

- task: Gitleaks@3
  inputs:
    scanlocation: '$(Build.SourcesDirectory)'
    configtype: 'predefined'
    predefinedconfigfile: 'GitleaksUdmCombo.toml'
    reportformat: 'sarif'
# - task: Gitleaks@3
#   inputs:
#     scanlocation: '$(Build.SourcesDirectory)'
#     configtype: 'predefined'
#     predefinedconfigfile: 'GitleaksUdmCombo.toml'
#     reportformat: 'sarif'
#     reportname: 'gitleaksfile'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/*.sarif'
    ArtifactName: 'drop'
    publishLocation: 'Container'